import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

/**
 * Curated sidebar for the ng-qubee documentation
 *
 * Order is the order users encounter concepts: install → choose a driver
 * → use the query builder → consume paginated responses → opt into
 * advanced features. Per-driver pages live in their own group so the
 * driver matrix is easy to scan.
 */
const sidebars: SidebarsConfig = {
  docsSidebar: [
    'getting-started',
    {
      type: 'category',
      label: 'Drivers',
      collapsed: false,
      items: [
        'drivers/json-api',
        'drivers/laravel',
        'drivers/spatie',
        'drivers/nestjs',
        'drivers/postgrest',
        'drivers/strapi'
      ]
    },
    'fetching-data',
    'query-builder',
    'pagination',
    'per-component-instances',
    {
      type: 'category',
      label: 'API Reference',
      collapsed: true,
      link: { type: 'generated-index', title: 'API Reference', description: 'Auto-generated from the library source. The contents mirror what `import { … } from \'ng-qubee\'` exposes.' },
      items: [{ type: 'autogenerated', dirName: 'api' }]
    }
  ]
};

export default sidebars;
